PublicationsLibrary/src/PublicationsLibrary/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using PublicationsLibrary.Models;
using PublicationsLibrary.ORM;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace PublicationsLibrary.Controllers
{
    public class SearchController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            if (Request.Cookies["userId"] != null)
            {
                if (SQLCreate.ExecuteSelectQuery("SELECT * FROM users where id=" + Request.Cookies["userId"]).Rows.Count > 0)
                {
                    return View();

                }

            }
            return View("Login");
        }
        [HttpGet]
        public ActionResult JsonRecent()
        {
            
            List<ArticleModel> models = new List<ArticleModel>();
            models.AddRange(Converter.ConvertArticle(SQLCreate.SelectQuery("articles", ArticleModel.fields, "random()<0.01 LIMIT 10"), ArticleModel.fields2));
            return Json(new { articles = models, max = 5 });
        }
        [HttpGet]
        public ActionResult Json(string query)
        {
            List<ArticleModel> models = new List<ArticleModel>();
            Dictionary<string, int> areas = new Dictionary<string, int>();
            List<string> finalAreas = new List<string>();
            List<int> areasItems = new List<int>();
            List<int> areasIDs = new List<int>();
            models = ORM.Converter.ConvertArticle(SQLCreate.SelectQuery("articles", ArticleModel.fields, "TITLE like '%"+Request.Query["search_string"]+"%' limit 15 offset " + int.Parse(Request.Query["page"])*15), ArticleModel.fields2).ToList();
            foreach (var model in models)
            {
                try
                {
                    areas.Add(model.ResearchArea.Name, 1);
                    areasIDs.Add(model.ResearchArea.ID);
                }
                catch
                {
                    areas[model.ResearchArea.Name]++;
                }

            }
            foreach (var a in areas)
            {
                finalAreas.Add(a.Key);
                areasItems.Add(a.Value);
            }
            return Json(new { max_id = models.Count, articles = models, areas = finalAreas, areasItems = areasItems, areasIDs = areasIDs, areas_cnt = areas.Count });
        }
    }
}

PublicationsLibrary/src/PublicationsLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - PublicationsLibrary</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
                  asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
                  asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
            <link rel="stylesheet" href="~/css/site.css" asp-file-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top navbar-material-blue-600">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">PublicationsLibrary</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Search" asp-action="Index">Search</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - PublicationsLibrary</p>
            </footer>
        </div>
      
        <environment names="Development">
            <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
            <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
            <script src="~/lib/bootstrap-material-design/scripts/material.js"></script>
            <script src="~/lib/bootstrap-material-design/scripts/ripples.js"></script>
            <script src="~/lib/hammer.js/hammer.js"></script>
            <script src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"></script>
            <script>
            $(document).ready(function () {
                // This command is used to initialize some elements and make them work properly
                $.material.init();
            });
            </script>
          </environment>
        <environment names="Staging,Production">
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                    asp-fallback-src="~/lib/hammer.js/hammer.js"
                    asp-fallback-test="window.Hammer">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
                    asp-fallback-src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"
                    asp-fallback-test="window.Hammer && window.Hammer.Instance">
            </script>
            <script src="~/js/site.js" asp-file-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>